# This file was generated by roxyPackage::roxy.package()
# and will likely be overwritten on its next run.
# Editing is futile.

#' \packageDescription{koRpus.lang.nl}
#'
#' The DESCRIPTION file:
#' \tabular{ll}{
#' Package: \tab koRpus.lang.nl\cr
#' Type: \tab Package\cr
#' Version: \tab 0.1-6\cr
#' Date: \tab 2022-07-07\cr
#' Depends: \tab R (>= 3.1),koRpus (>= 0.11-2)\cr
#' Encoding: \tab UTF-8\cr
#' License: \tab GPL (>= 3)\cr
#' LazyLoad: \tab yes\cr
#' URL: \tab https://reaktanz.de/?c=hacking&s=koRpus\cr
#' }
#'
#' @title
#' \packageTitle{koRpus.lang.nl}
#' @author
#' \packageAuthor{koRpus.lang.nl}
#'
#' Maintainer: \packageMaintainer{koRpus.lang.nl}
"_PACKAGE"

## usethis namespace: start
## usethis namespace: end
NULL